//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internet_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public decimal ID { get; set; }
        public string FullName { get; set; }
        public string Position { get; set; }
        public string Gender { get; set; }
        public string Salary { get; set; }
    }
}
